# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1667ff0c860877cd44aceb2a757403b66a93d2a33c8c8b7a138749b5f8ee5a4237c3b343de076e8b4d5668be5b20a238aa562eee8f63be484bfe6de9a5641906

test:
  secret_key_base: ea0f237675d94e628a404fe50650a4f4d0079f600444dfb6ac3cfd6956234fdc915b98d7176d78aaef907b0dc944903e46ba043a55d9da0cb0765a534c618c04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
